import Link from "next/link";
import type { RowDataPacket } from "mysql2";
import { db } from "@/lib/db";
import { formatNumber } from "@/lib/format";

async function dashboardData() {
  try {
    const pool = db();
    const [leadRows] = await pool.query<RowDataPacket[]>("SELECT COUNT(*) AS total FROM leads");
    const [projectRows] = await pool.query<RowDataPacket[]>("SELECT COUNT(*) AS total FROM projects WHERE status <> 'ARCHIVED'");
    const [publishedRows] = await pool.query<RowDataPacket[]>("SELECT (SELECT COUNT(*) FROM promotions WHERE is_published=TRUE) + (SELECT COUNT(*) FROM news_items WHERE is_published=TRUE) AS total");
    const [recentRows] = await pool.query<RowDataPacket[]>("SELECT l.name, l.phone, l.status, l.created_at, p.name_th AS project_name FROM leads l LEFT JOIN projects p ON p.id=l.project_id ORDER BY l.created_at DESC LIMIT 5");
    return { leads: Number(leadRows[0].total), projects: Number(projectRows[0].total), published: Number(publishedRows[0].total), recent: recentRows };
  } catch { return { leads: 0, projects: 0, published: 0, recent: [] as RowDataPacket[] }; }
}

export default async function AdminPage() {
  const data = await dashboardData();
  const stats = [["โครงการ", formatNumber(data.projects), "/admin/projects"], ["ผู้ลงทะเบียน", formatNumber(data.leads), "/admin/leads"], ["เนื้อหาที่เผยแพร่", formatNumber(data.published), "/admin/promotions"]];
  return <><header className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#F5A623]">DASHBOARD MD</p><h1 className="mt-1 text-3xl font-extrabold text-[#002D62]">ภาพรวมระบบ</h1><p className="mt-2 text-sm text-slate-500">จัดการข้อมูลเว็บไซต์และติดตามผู้สนใจโครงการ</p></div><span className="rounded-full bg-white px-3 py-2 text-xs font-bold text-slate-500 shadow-sm">{new Date().toLocaleDateString("th-TH")}</span></header><div className="mt-8 grid gap-4 md:grid-cols-3">{stats.map(([label, value, href]) => <Link key={label} href={href} className="rounded-2xl bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-3xl font-extrabold text-[#002D62]">{value}</p><p className="mt-3 text-xs font-bold text-[#F5A623]">จัดการข้อมูล →</p></Link>)}</div><div className="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-extrabold text-[#002D62]">ผู้ลงทะเบียนล่าสุด</h2><p className="mt-1 text-sm text-slate-500">ข้อมูลจากแบบฟอร์มหน้าเว็บไซต์</p></div><Link href="/admin/leads" className="text-sm font-bold text-[#002D62]">ดูทั้งหมด →</Link></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-120 text-left text-sm"><thead className="border-b text-xs text-slate-400"><tr><th className="pb-3">ชื่อ</th><th className="pb-3">โครงการ</th><th className="pb-3">สถานะ</th><th className="pb-3">วันที่</th></tr></thead><tbody>{data.recent.length ? data.recent.map((lead) => <tr key={`${lead.name}-${lead.created_at}`} className="border-b border-slate-100"><td className="py-3 font-semibold">{lead.name}<span className="block text-xs font-normal text-slate-400">{lead.phone}</span></td><td className="py-3">{lead.project_name ?? "เว็บไซต์กลาง"}</td><td className="py-3"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-[#002D62]">{lead.status}</span></td><td className="py-3 text-slate-500">{new Date(lead.created_at).toLocaleDateString("th-TH")}</td></tr>) : <tr><td colSpan={4} className="py-10 text-center text-slate-400">ยังไม่มีข้อมูลผู้ลงทะเบียน</td></tr>}</tbody></table></div></section><section className="rounded-2xl bg-[#002D62] p-6 text-white"><p className="text-sm font-bold text-[#f8c366]">QUICK ACTIONS</p><h2 className="mt-2 text-xl font-extrabold">จัดการเว็บไซต์</h2><div className="mt-6 space-y-2">{[["เพิ่มโครงการ", "/admin/projects"], ["สร้างโปรโมชั่น", "/admin/promotions"], ["เพิ่มข่าวสาร", "/admin/news"], ["แก้ไขข้อความหน้าเว็บ", "/admin/content"]].map(([label, href]) => <Link key={href} href={href} className="flex items-center justify-between rounded-xl bg-white/10 px-4 py-3 text-sm font-bold hover:bg-white/20">{label}<span>→</span></Link>)}</div></section></div></>;
}
